#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"

STORAGE_PATH="${DOKKU_ROOT}/${APP}/data"
mkdir -p $STORAGE_PATH

echo "$STDIN --env=APP=$APP"

echo "$STDIN --volume=$STORAGE_PATH:/data"
echo "$STDIN --volume=/data/pulseaudio:/var/run/pulse"
echo "$STDIN --volume=/data/hardware:/hardware"

