#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"

TECHNOLOGIE=$(docker run --rm -t ${IMAGE} bash -c '
  buildpack_path=/tmp/buildpacks
  build_path=/app
  selected_name="none"
  if [[ "$selected_name" = "none" ]]; then
    buildpacks=($buildpack_path/*)
    for buildpack in "${buildpacks[@]}"; do
      selected_name="$($buildpack/bin/detect $build_path)" && break
    done
  fi
  echo $selected_name
')
echo $TECHNOLOGIE > $DOKKU_ROOT/$APP/TECHNOLOGIE
